export const ErrorMap: Record<string, string> = {
  UNKNOWN_ERROR: "response.error.UNKNOWN_ERROR",
  CATEGORY_ALREADY_EXISTS_EXCEPTION: "response.error.CATEGORY_EXISTS",
  CLIENT_PHONE_ALREADY_EXISTS: "response.error.CLIENT_PHONE_ALREADY_EXISTS",
  SUBCATEGORY_ALREADY_EXISTS_EXCEPTION: "response.error.SUBCATEGORY_EXISTS",
  SERVER_WEB_INPUT_EXCEPTION: "response.error.SERVER_WEB_INPUT_EXCEPTION",
  ILLEGAL_ARGUMENT_EXCEPTION: "response.error.ILLEGAL_ARGUMENT",
  EMAIL_IS_ALREADY_REGISTERED_EXCEPTION: "response.error.EMAIL_REGISTERED",
  INVALID_CREDENTIALS_EXCEPTION: "response.error.INVALID_CREDENTIALS",
};
